FROM ruby:3.4.1

# Install dependencies including PostgreSQL client
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs npm vim

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

# Add a script to be executed every time the container starts.
COPY bin/docker-entrypoint /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint
ENTRYPOINT ["docker-entrypoint"]

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
